### ISSUE TITLE
리뷰 남깁니다!

### ISSUE THREAD

**Issue by Hwwane** [devmizz/SSG#10]
좋은점
- 응용한 코드들이 많이 보여서 좋았습니다!
- 패키지 별로 깔끔하게 정리 되어 있어 이해가 어렵지 않았습니다
- 코드도 깔끔하게 되어있어 좋았습니다!

아쉬운 점
- 없습니다!

좋은 코드 잘 봤습니다!

**Comment by devmizz** [comment]
👍
