### ISSUE TITLE
리뷰 남깁니다!

### ISSUE THREAD

**Issue by Jwhyee** [devmizz/SSG#2]
## 좋은 점
- 관심사 별로 패키징한게 정말 인상 깊었습니다!!
- 또한 App.java 수정 로직에서도 람다식을 활용하셔서 코드가 깔끔해진 것 같아요!
## 아쉬운 점
- 아쉬운 점은 없었습니다!

좋은 코드 보여주셔서 감사합니다!
수고하셨습니다!

**Comment by devmizz** [comment]
👍
