### ISSUE TITLE
리뷰 남깁니다.

### ISSUE THREAD

**Issue by qkrtpgh5033** [devmizz/SSG#5]
#좋은점
- 각 역할들을 폴더로 나누셔서 프로젝트 구조를 파악하기 편했습니다.
- find 메소드에서 Optional을 통해 Null값 처리하신 점이 좋았습니다
- id.json 파일을 통해 빠르게 마지막 Id 값을 알 수 있게 하신 점이 센스 있으신거 같습니다!

#아쉬운점 -> 궁금한점
- Sayings 클래스에서 id의 의미가 무엇인가요?? 
  만약 마지막 Id값을 의미하는 거라면 lastId라고 변수명을 짓는게 어땠을까요?
- Post 클래스에 Id를 안두시고, 별도로 클래스를 두신 이유가 궁금합니다.

전체적으로 코드에 신경을 쓰신게 보여서 깔끔한거 같습니다.
많이 배웠습니다. 감사합니다!

**Comment by devmizz** [comment]
저는 게시글 자체의 id와, 보통 DB에서 사용되는 id(identity)를 구분하고자 했습니다!
그래서 해당 정보를 함께 옮겨야 할 때 사용되는 DTO로서, id(identity)와 Saying(id, content, author)로 구성된 데이터를 넘기는 역할을 합니다! 보통 테이블에서 사용되는 id를 위해 Entity 모델에서 'id'라는 네이밍을 사용합니다! 그래서 'lastId'라고 명명하지 않았습니다.
Post 클래스와 Saying 클래스는 id의 유무 차이인데, 사실 둘을 합치고 생성자로 구분해도 되는 부분이긴 합니다. 그래도 역할에 구분이 있다고 생각을 했고, Post 클래스는 유저가 id를 입력할 필요가 없는 경우(등록), 그 외에는 Saying 클래스를 사용하고자 했습니다.

꼼꼼한 코멘트 감사합니다!

**Comment by qkrtpgh5033** [comment]
아하 Entity 모델 개념으로 id를 사용하신 거군요
디테일 하시네요 많이 배웠습니다!!
