### ISSUE TITLE
리뷰 남깁니다.

### ISSUE THREAD

**Issue by jyajoo** [devmizz/SSG#7]
회고록 피드백 시간에 DTO에 대해 언급해주셨었는데, 
코드를 살펴보니 DTO를 이용해서 데이터 객체를 전달해주는 것을 직접 살펴볼 수 있어서 좋았어요.! ㅎㅎ

수고하셨습니다~

**Comment by devmizz** [comment]
기억해주시니 감사합니다! 👍
