### ISSUE TITLE
리뷰 남깁니다.

### ISSUE THREAD

**Issue by seeunla** [devmizz/SSG#8]
좋았던 점
- 코드 하나하나 신경써서 짜신 게 느껴져서 좋았습니다.
- 본인만의 루틴이나 개요 짜는 방법 같은 것들이 보여서 많이 배웠습니다.
- 폴더 관리가 깔끔해서 보면서 잘 이해가 되었습니다. 
- 몰랐던 문법들을 새로 보게 되어 공부가 되었습니다.

아쉬웠던 점
- 없습니다.

코드 짜느라 고생 많으셨습니다. 좋은 코드 공유해주셔서 감사하고 많이 배워갑니다.

**Comment by devmizz** [comment]
👍
