### ISSUE TITLE
코드 리뷰 남깁니다!

### ISSUE THREAD

**Issue by ahah525** [devmizz/SSG#9]
# 좋은점
- 레이어별로 디렉토리 분리를 해서 더 보기 좋은 것 같아요!
- dto를 이용한신 부분이 좋았고 시간 여유가 되면 저도 그렇게 구현해보고 싶네요!
- 커밋 관리도 깔끔하게 잘하신 것 같고 전반적으로 코드도 깔끔해서 좋았어요!

# 아쉬운 점
- 없음

수고하셨고 많이 배우고 갑니다!

**Comment by devmizz** [comment]
👍
